# Generated by Django 3.2.2 on 2021-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210513_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
